// https://gitmoji.dev/
export const emoji = [
  {
    emoji: '🎨',
    code: ':art:',
    description: 'Improve structure / format of the code.',
    description_zh: '改进代码的结构/格式。',
  },
  {
    emoji: '⚡️',
    code: ':zap:',
    description: 'Improve performance.',
    description_zh: '提高性能。',
  },
  {
    emoji: '🔥',
    code: ':fire:',
    description: 'Remove code or files.',
    description_zh: '删除代码或文件。',
  },
  {
    emoji: '🐛',
    code: ':bug:',
    description: 'Fix a bug.',
    description_zh: '修复错误。',
  },
  {
    emoji: '🚑️',
    code: ':ambulance:',
    description: 'Critical hotfix.',
    description_zh: '重要补丁。',
  },
  {
    emoji: '✨',
    code: ':sparkles:',
    description: 'Introduce new features.',
    description_zh: '引入新功能。',
  },
  {
    emoji: '📝',
    code: ':memo:',
    description: 'Add or update documentation.',
    description_zh: '添加或更新文档。',
  },
  {
    emoji: '🚀',
    code: ':rocket:',
    description: 'Deploy stuff.',
    description_zh: '部署内容。',
  },
  {
    emoji: '💄',
    code: ':lipstick:',
    description: 'Add or update the UI and style files.',
    description_zh: '添加或更新 UI 和样式文件。',
  },
  {
    emoji: '🎉',
    code: ':tada:',
    description: 'Begin a project.',
    description_zh: '初次提交。',
  },
  {
    emoji: '✅',
    code: ':white_check_mark:',
    description: 'Add, update, or pass tests.',
    description_zh: '添加、更新或通过测试。',
  },
  {
    emoji: '🔒️',
    code: ':lock:',
    description: 'Fix security issues.',
    description_zh: '修复安全问题。',
  },
  {
    emoji: '🔐',
    code: ':closed_lock_with_key:',
    description: 'Add or update secrets.',
    description_zh: '添加或更新机密。',
  },
  {
    emoji: '🔖',
    code: ':bookmark:',
    description: 'Release / Version tags.',
    description_zh: '发布/版本标记。',
  },
  {
    emoji: '🚨',
    code: ':rotating_light:',
    description: 'Fix compiler / linter warnings.',
    description_zh: '修复编译器/棉绒警告。',
  },
  {
    emoji: '🚧',
    code: ':construction:',
    description: 'Work in progress.',
    description_zh: '工作正在进行中。',
  },
  {
    emoji: '💚',
    code: ':green_heart:',
    description: 'Fix CI Build.',
    description_zh: '修复 CI 生成。',
  },
  {
    emoji: '⬇️',
    code: ':arrow_down:',
    description: 'Downgrade dependencies.',
    description_zh: '降级依赖项。',
  },
  {
    emoji: '⬆️',
    code: ':arrow_up:',
    description: 'Upgrade dependencies.',
    description_zh: '升级依赖项。',
  },
  {
    emoji: '📌',
    code: ':pushpin:',
    description: 'Pin dependencies to specific versions.',
    description_zh: '将依赖项固定到特定版本。',
  },
  {
    emoji: '👷',
    code: ':construction_worker:',
    description: 'Add or update CI build system.',
    description_zh: '添加或更新 CI 构建系统。',
  },
  {
    emoji: '📈',
    code: ':chart_with_upwards_trend:',
    description: 'Add or update analytics or track code.',
    description_zh: '添加或更新分析或跟踪代码。',
  },
  {
    emoji: '♻️',
    code: ':recycle:',
    description: 'Refactor code.',
    description_zh: '重构代码。',
  },
  {
    emoji: '➕',
    code: ':heavy_plus_sign:',
    description: 'Add a dependency.',
    description_zh: '添加依赖项。',
  },
  {
    emoji: '➖',
    code: ':heavy_minus_sign:',
    description: 'Remove a dependency.',
    description_zh: '删除依赖项。',
  },
  {
    emoji: '🔧',
    code: ':wrench:',
    description: 'Add or update configuration files.',
    description_zh: '添加或更新配置文件。',
  },
  {
    emoji: '🔨',
    code: ':hammer:',
    description: 'Add or update development scripts.',
    description_zh: '添加或更新开发脚本。',
  },
  {
    emoji: '🌐',
    code: ':globe_with_meridians:',
    description: 'Internationalization and localization.',
    description_zh: '国际化和本地化。',
  },
  {
    emoji: '✏️',
    code: ':pencil2:',
    description: 'Fix typos.',
    description_zh: '修正拼写错误。',
  },
  {
    emoji: '💩',
    code: ':poop:',
    description: 'Write bad code that needs to be improved.',
    description_zh: '编写需要改进的不良代码。',
  },
  {
    emoji: '⏪️',
    code: ':rewind:',
    description: 'Revert changes.',
    description_zh: '还原更改、回滚代码。',
  },
  {
    emoji: '🔀',
    code: ':twisted_rightwards_arrows:',
    description: 'Merge branches.',
    description_zh: '合并分支。',
  },
  {
    emoji: '📦️',
    code: ':package:',
    description: 'Add or update compiled files or packages.',
    description_zh: '添加或更新已编译的文件或包。',
  },
  {
    emoji: '👽️',
    code: ':alien:',
    description: 'Update code due to external API changes.',
    description_zh: '由于外部 API 更改而更新代码。',
  },
  {
    emoji: '🚚',
    code: ':truck:',
    description: 'Move or rename resources (e.g.: files, paths, routes).',
    description_zh: '移动或重命名资源（例如：文件、路径、路由）。',
  },
  {
    emoji: '📄',
    code: ':page_facing_up:',
    description: 'Add or update license.',
    description_zh: '添加或更新许可证。',
  },
  {
    emoji: '💥',
    code: ':boom:',
    description: 'Introduce breaking changes.',
    description_zh: '引入中断性变更。',
  },
  {
    emoji: '🍱',
    code: ':bento:',
    description: 'Add or update assets.',
    description_zh: '添加或更新资产。',
  },
  {
    emoji: '♿️',
    code: ':wheelchair:',
    description: 'Improve accessibility.',
    description_zh: '提高可访问性。',
  },
  {
    emoji: '💡',
    code: ':bulb:',
    description: 'Add or update comments in source code.',
    description_zh: '在源代码中添加或更新注释。',
  },
  {
    emoji: '🍻',
    code: ':beers:',
    description: 'Write code drunkenly.',
    description_zh: '醉醺醺地写代码。',
  },
  {
    emoji: '💬',
    code: ':speech_balloon:',
    description: 'Add or update text and literals.',
    description_zh: '添加或更新文本和文字。',
  },
  {
    emoji: '🗃️',
    code: ':card_file_box:',
    description: 'Perform database related changes.',
    description_zh: '执行与数据库相关的更改。',
  },
  {
    emoji: '🔊',
    code: ':loud_sound:',
    description: 'Add or update logs.',
    description_zh: '添加或更新日志。',
  },
  {
    emoji: '🔇',
    code: ':mute:',
    description: 'Remove logs.',
    description_zh: '删除日志。',
  },
  {
    emoji: '👥',
    code: ':busts_in_silhouette:',
    description: 'Add or update contributor(s).',
    description_zh: '添加或更新参与者。',
  },
  {
    emoji: '🚸',
    code: ':children_crossing:',
    description: 'Improve user experience / usability.',
    description_zh: '改善用户体验/可用性。',
  },
  {
    emoji: '🏗️',
    code: ':building_construction:',
    description: 'Make architectural changes.',
    description_zh: '进行体系结构更改。',
  },
  {
    emoji: '📱',
    code: ':iphone:',
    description: 'Work on responsive design.',
    description_zh: '致力于响应式设计。',
  },
  {
    emoji: '🤡',
    code: ':clown_face:',
    description: 'Mock things.',
    description_zh: '模拟事物。',
  },
  {
    emoji: '🥚',
    code: ':egg:',
    description: 'Add or update an easter egg.',
    description_zh: '添加或更新复活节彩蛋。',
  },
  {
    emoji: '🙈',
    code: ':see_no_evil:',
    description: 'Add or update a .gitignore file.',
    description_zh: '添加或更新 .gitignore 文件。',
  },
  {
    emoji: '📸',
    code: ':camera_flash:',
    description: 'Add or update snapshots.',
    description_zh: '添加或更新快照。',
  },
  {
    emoji: '⚗️',
    code: ':alembic:',
    description: 'Perform experiments.',
    description_zh: '进行实验。',
  },
  {
    emoji: '🔍️',
    code: ':mag:',
    description: 'Improve SEO.',
    description_zh: '改善搜索引擎优化。',
  },
  {
    emoji: '🏷️',
    code: ':label:',
    description: 'Add or update types.',
    description_zh: '添加或更新类型。',
  },
  {
    emoji: '🌱',
    code: ':seedling:',
    description: 'Add or update seed files.',
    description_zh: '添加或更新种子文件。',
  },
  {
    emoji: '🚩',
    code: ':triangular_flag_on_post:',
    description: 'Add, update, or remove feature flags.',
    description_zh: '添加、更新或删除功能标志。',
  },
  {
    emoji: '🥅',
    code: ':goal_net:',
    description: 'Catch errors.',
    description_zh: '捕获错误。',
  },
  {
    emoji: '💫',
    code: ':dizzy:',
    description: 'Add or update animations and transitions.',
    description_zh: '添加或更新动画和过渡。',
  },
  {
    emoji: '🗑️',
    code: ':wastebasket:',
    description: 'Deprecate code that needs to be cleaned up.',
    description_zh: '弃用需要清理的代码。',
  },
  {
    emoji: '🛂',
    code: ':passport_control:',
    description: 'Work on code related to authorization, roles and permissions.',
    description_zh: '处理与授权、角色和权限相关的代码。',
  },
  {
    emoji: '🩹',
    code: ':adhesive_bandage:',
    description: 'Simple fix for a non-critical issue.',
    description_zh: '非关键问题的简单修复。',
  },
  {
    emoji: '🧐',
    code: ':monocle_face:',
    description: 'Data exploration/inspection.',
    description_zh: '数据探索/检查。',
  },
  {
    emoji: '⚰️',
    code: ':coffin:',
    description: 'Remove dead code.',
    description_zh: '删除死代码。',
  },
  {
    emoji: '🧪',
    code: ':test_tube:',
    description: 'Add a failing test.',
    description_zh: '添加失败的测试。',
  },
  {
    emoji: '👔',
    code: ':necktie:',
    description: 'Add or update business logic.',
    description_zh: '添加或更新业务逻辑。',
  },
  {
    emoji: '🩺',
    code: ':stethoscope:',
    description: 'Add or update healthcheck.',
    description_zh: '添加或更新运行状况检查。',
  },
  {
    emoji: '🧱',
    code: ':bricks:',
    description: 'Infrastructure related changes.',
    description_zh: '基础设施相关变更。',
  },
  {
    emoji: '🧑‍💻',
    code: ':technologist:',
    description: 'Improve developer experience.',
    description_zh: '改善开发人员体验。',
  },
  {
    emoji: '💸',
    code: ':money_with_wings:',
    description: 'Add sponsorships or money related infrastructure.',
    description_zh: '添加赞助或与金钱相关的基础设施。',
  },
  {
    emoji: '🧵',
    code: ':thread:',
    description: 'Add or update code related to multithreading or concurrency.',
    description_zh: '添加或更新与多线程或并发相关的代码。',
  },
  {
    emoji: '🦺',
    code: ':safety_vest:',
    description: 'Add or update code related to validation.',
    description_zh: '添加或更新与验证相关的代码。',
  },
];
